CREATE DATABASE IF NOT EXISTS ppw1
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE ppw1;

CREATE TABLE IF NOT EXISTS prodi (
  id   INT PRIMARY KEY AUTO_INCREMENT,
  nama VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mahasiswa (
  id         INT PRIMARY KEY AUTO_INCREMENT,
  nama       VARCHAR(100)   NOT NULL,
  nim        VARCHAR(20)    NOT NULL UNIQUE,
  prodi_id   INT            NOT NULL,
  ipk        DECIMAL(3,2)   NOT NULL,
  semester   TINYINT        NOT NULL,
  created_at TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (prodi_id) REFERENCES prodi(id)
);

INSERT INTO prodi (nama) VALUES
('Agronomi'),
('Akuntansi'),
('Arkeologi'),
('Arsitektur'),
('Bahasa dan Kebudayaan Korea'),
('Bahasa dan Sastra Indonesia'),
('Biologi'),
('Bioteknologi'),
('Elektronika dan Instrumentasi'),
('Farmasi'),
('Filsafat'),
('Fisika'),
('Geofisika'),
('Geografi dan Ilmu Lingkungan'),
('Geologi'),
('Higiene Gigi'),
('Hukum'),
('Ilmu Aktuaria'),
('Ilmu Ekonomi'),
('Ilmu Hubungan Internasional'),
('Ilmu Keperawatan'),
('Ilmu Komunikasi'),
('Ilmu Komputer'),
('Ilmu Pemerintahan'),
('Ilmu Sejarah'),
('Informatika'),
('Kedokteran'),
('Kedokteran Gigi'),
('Kedokteran Hewan'),
('Kehutanan'),
('Kimia'),
('Manajemen'),
('Manajemen dan Kebijakan Publik'),
('Matematika'),
('Mikrobiologi Pertanian'),
('Nutrisi dan Kesehatan Hewan'),
('Pariwisata'),
('Pembangunan Wilayah'),
('Pembangunan Sosial dan Kesejahteraan'),
('Pendidikan Dokter'),
('Penyuluhan dan Komunikasi Pertanian'),
('Perencanaan Wilayah dan Kota'),
('Pertanian'),
('Peternakan'),
('Psikologi'),
('Sastra Arab'),
('Sastra Indonesia'),
('Sastra Inggris'),
('Sastra Jawa'),
('Sastra Jepang'),
('Sastra Nusantara'),
('Sastra Perancis'),
('Sastra Yunani dan Latin'),
('Seni Murni'),
('Seni Pertunjukan'),
('Seni Rupa'),
('Sistem Informasi'),
('Sosiologi'),
('Statistika'),
('Teknologi Informasi'),
('Teknik Biomedis'),
('Teknik Elektro'),
('Teknik Fisika'),
('Teknik Geodesi'),
('Teknik Geologi'),
('Teknik Industri'),
('Teknik Kimia'),
('Teknik Mesin'),
('Teknik Nuklir'),
('Teknik Pertanian'),
('Teknik Sipil'),
('Teknik Infrastruktur Lingkungan'),
('Teknologi Hasil Hutan'),
('Teknologi Hasil Perikanan'),
('Teknologi Industri Pertanian'),
('Teknologi Pangan dan Hasil Pertanian'),
('Teknologi Rekayasa Instrumentasi dan Kontrol'),
('Teknologi Rekayasa Mesin'),
('Teknologi Rekayasa Pelaksanaan Bangunan Sipil'),
('Teknologi Rekayasa Perangkat Lunak'),
('Teknologi Rekayasa Elektro'),
('Teknologi Veteriner'),
('Usaha Perjalanan Wisata'),
('Manajemen Informasi'),
('Manajemen Sumber Daya Akuatik'),
('Pengelolaan Hutan'),
('Proteksi Tanaman'),
('Bisnis Internasional'),
('Bisnis Perjalanan Wisata'),
('Antropologi Budaya'),
('Ekonomi Terapan');
